SET NAMES utf8mb4;
USE curriculum_iu;

START TRANSACTION;

UPDATE course SET name_vn = 'Hóa học cho Kỹ sư' WHERE course_code = 'CH011IU';
UPDATE course SET name_vn = 'Thực hành Hóa học' WHERE course_code = 'CH012IU';
UPDATE course SET name_vn = 'Nguyên lý Điện tử 1' WHERE course_code = 'EE051IU';
UPDATE course SET name_vn = 'Nguyên lý Điện tử 1' WHERE course_code = 'EE052IU';
UPDATE course SET name_vn = 'Thiết kế Logic Số' WHERE course_code = 'EE053IU';
UPDATE course SET name_vn = 'Thiết kế Logic Số' WHERE course_code = 'EE054IU';
UPDATE course SET name_vn = 'Thiết kế Hệ thống Số' WHERE course_code = 'EE063IU';
UPDATE course SET name_vn = 'Khái niệm về Thiết kế VLSI' WHERE course_code = 'EE066IU';
UPDATE course SET name_vn = 'Hệ thống Vi xử lý' WHERE course_code = 'EE083IU';
UPDATE course SET name_vn = 'Thực hành Hệ thống Vi xử lý' WHERE course_code = 'EE084IU';
UPDATE course SET name_vn = 'Electronics Devices' WHERE course_code = 'EE090IU';
UPDATE course SET name_vn = 'Electronics Devices' WHERE course_code = 'EE091IU';
UPDATE course SET name_vn = 'Xử lý Tín hiệu Số' WHERE course_code = 'EE092IU';
UPDATE course SET name_vn = 'Thực hành Xử lý Tín hiệu Số' WHERE course_code = 'EE093IU';
UPDATE course SET name_vn = 'Hệ thống Nhúng' WHERE course_code = 'EE104IU';
UPDATE course SET name_vn = 'Thiết kế Hệ thống Số' WHERE course_code = 'EE117IU';
UPDATE course SET name_vn = 'Hệ thống Nhúng' WHERE course_code = 'EE118IU';
UPDATE course SET name_vn = 'Concepts in VLSI Design f) Bachelor of Engineering in' WHERE course_code = 'EE121IU';
UPDATE course SET name_vn = 'Tiếng Anh học thuật 1 (Viết)' WHERE course_code = 'EN007IU';
UPDATE course SET name_vn = 'Tiếng Anh học thuật 1 (Nghe)' WHERE course_code = 'EN008IU';
UPDATE course SET name_vn = 'Tiếng Anh học thuật 2 (Viết bài nghiên cứu)' WHERE course_code = 'EN011IU';
UPDATE course SET name_vn = 'Tiếng Anh học thuật 2 (Thuyết trình)' WHERE course_code = 'EN012IU';
UPDATE course SET name_vn = 'Giải thuật và Cấu trúc Dữ liệu' WHERE course_code = 'IT013IU';
UPDATE course SET name_vn = 'Hệ điều hành' WHERE course_code = 'IT017IU';
UPDATE course SET name_vn = 'Đồ họa Máy tính' WHERE course_code = 'IT024IU';
UPDATE course SET name_vn = 'Quản lý Dự án CNTT' WHERE course_code = 'IT056IU';
UPDATE course SET name_vn = 'Luận văn tốt nghiệp' WHERE course_code = 'IT058IU';
UPDATE course SET name_vn = 'Nhập môn Máy tính' WHERE course_code = 'IT064IU';
UPDATE course SET name_vn = 'Thiết kế Logic Số' WHERE course_code = 'IT067IU';
UPDATE course SET name_vn = 'Nguyên lý Kỹ thuật Điện I' WHERE course_code = 'IT068IU';
UPDATE course SET name_vn = 'Lập trình Hướng đối tượng' WHERE course_code = 'IT069IU';
UPDATE course SET name_vn = 'Linh kiện Điện tử' WHERE course_code = 'IT074IU';
UPDATE course SET name_vn = 'Công nghệ Phần mềm' WHERE course_code = 'IT076IU';
UPDATE course SET name_vn = 'Quản lý Cơ sở Dữ liệu' WHERE course_code = 'IT079IU';
UPDATE course SET name_vn = 'Thực tập' WHERE course_code = 'IT082IU';
UPDATE course SET name_vn = 'Đồ án Đặc biệt của Ngành' WHERE course_code = 'IT083IU';
UPDATE course SET name_vn = 'Kiến trúc Máy tính' WHERE course_code = 'IT089IU';
UPDATE course SET name_vn = 'Phân tích và Thiết kế Hướng đối tượng' WHERE course_code = 'IT090IU';
UPDATE course SET name_vn = 'Mạng Máy tính' WHERE course_code = 'IT091IU';
UPDATE course SET name_vn = 'Nguyên lý Ngôn ngữ Lập trình' WHERE course_code = 'IT092IU';
UPDATE course SET name_vn = 'Phát triển Ứng dụng Web' WHERE course_code = 'IT093IU';
UPDATE course SET name_vn = 'Quản lý Hệ thống Thông tin' WHERE course_code = 'IT094IU';
UPDATE course SET name_vn = 'Lập trình Hướng mạng' WHERE course_code = 'IT096IU';
UPDATE course SET name_vn = 'Nguyên lý Kỹ thuật Điện I' WHERE course_code = 'IT098IU';
UPDATE course SET name_vn = 'Thực hành Thiết kế Logic Số' WHERE course_code = 'IT099IU';
UPDATE course SET name_vn = 'Linh kiện Điện tử' WHERE course_code = 'IT101IU';
UPDATE course SET name_vn = 'Xử lý Tín hiệu Số' WHERE course_code = 'IT103IU';
UPDATE course SET name_vn = 'Thiết kế Hệ thống Số' WHERE course_code = 'IT105IU';
UPDATE course SET name_vn = 'Thực hành Thiết kế Hệ thống Số' WHERE course_code = 'IT106IU';
UPDATE course SET name_vn = 'Khái niệm về Thiết kế VLSI' WHERE course_code = 'IT110IU';
UPDATE course SET name_vn = 'Kiến trúc Phần mềm' WHERE course_code = 'IT114IU';
UPDATE course SET name_vn = 'Hệ thống Nhúng' WHERE course_code = 'IT115IU';
UPDATE course SET name_vn = 'Lập trình C/C++' WHERE course_code = 'IT116IU';
UPDATE course SET name_vn = 'Bảo mật Hệ thống và Mạng' WHERE course_code = 'IT117IU';
UPDATE course SET name_vn = 'Khởi nghiệp' WHERE course_code = 'IT120IU';
UPDATE course SET name_vn = 'Quản trị Hệ thống và Mạng' WHERE course_code = 'IT125IU';
UPDATE course SET name_vn = 'Khái niệm về VLSI' WHERE course_code = 'IT126IU';
UPDATE course SET name_vn = 'Hệ thống Nhúng' WHERE course_code = 'IT127IU';
UPDATE course SET name_vn = 'Hệ thống Vi xử lý' WHERE course_code = 'IT128IU';
UPDATE course SET name_vn = 'Thực hành Hệ thống Vi xử lý' WHERE course_code = 'IT129IU';
UPDATE course SET name_vn = 'Xử lý Ảnh Kỹ thuật số' WHERE course_code = 'IT130IU';
UPDATE course SET name_vn = 'Mô hình Lý thuyết trong Tính toán' WHERE course_code = 'IT131IU';
UPDATE course SET name_vn = 'Phát triển Ứng dụng Di động' WHERE course_code = 'IT133IU';
UPDATE course SET name_vn = 'Internet of Things' WHERE course_code = 'IT134IU';
UPDATE course SET name_vn = 'Nhập môn Khoa học Dữ liệu' WHERE course_code = 'IT135IU';
UPDATE course SET name_vn = 'Phân tích Hồi quy' WHERE course_code = 'IT136IU';
UPDATE course SET name_vn = 'Phân tích Dữ liệu' WHERE course_code = 'IT137IU';
UPDATE course SET name_vn = 'Khoa học Dữ liệu và Trực quan hóa' WHERE course_code = 'IT138IU';
UPDATE course SET name_vn = 'Tính toán Phân tán và Có khả năng mở rộng' WHERE course_code = 'IT139IU';
UPDATE course SET name_vn = 'Cơ sở Bảo mật Dữ liệu' WHERE course_code = 'IT140IU';
UPDATE course SET name_vn = 'Phân tích Dữ liệu Quan sát' WHERE course_code = 'IT142IU';
UPDATE course SET name_vn = 'Phân tích Quy trình Kinh doanh' WHERE course_code = 'IT144IU';
UPDATE course SET name_vn = 'Hệ thống Hỗ trợ Quyết định' WHERE course_code = 'IT145IU';
UPDATE course SET name_vn = 'Lý thuyết Mạng' WHERE course_code = 'IT146IU';
UPDATE course SET name_vn = 'Điện toán Đám mây Di động' WHERE course_code = 'IT147IU';
UPDATE course SET name_vn = 'Thiết kế Thực nghiệm' WHERE course_code = 'IT148IU';
UPDATE course SET name_vn = 'Cơ bản về Lập trình' WHERE course_code = 'IT149IU';
UPDATE course SET name_vn = 'Blockchain' WHERE course_code = 'IT150IU';
UPDATE course SET name_vn = 'Phương pháp Thống kê' WHERE course_code = 'IT151IU';
UPDATE course SET name_vn = 'Khai thác Dữ liệu cho IoT' WHERE course_code = 'IT152IU';
UPDATE course SET name_vn = 'Toán rời rạc' WHERE course_code = 'IT153IU';
UPDATE course SET name_vn = 'Đại số tuyến tính' WHERE course_code = 'IT154IU';
UPDATE course SET name_vn = 'Phát triển và Vận hành (DevOps)' WHERE course_code = 'IT156IU';
UPDATE course SET name_vn = 'Học sâu (Deep Learning)' WHERE course_code = 'IT157IU';
UPDATE course SET name_vn = 'Thiết kế và Đánh giá Giao diện' WHERE course_code = 'IT158IU';
UPDATE course SET name_vn = 'Trí tuệ Nhân tạo' WHERE course_code = 'IT159IU';
UPDATE course SET name_vn = 'Khai thác Dữ liệu' WHERE course_code = 'IT160IU';
UPDATE course SET name_vn = 'Công nghệ Dữ liệu Lớn' WHERE course_code = 'IT161IU';
UPDATE course SET name_vn = 'Nền tảng Học máy' WHERE course_code = 'IT162IU';
UPDATE course SET name_vn = 'Tối ưu hóa và Ứng dụng' WHERE course_code = 'IT163IU';
UPDATE course SET name_vn = 'Giải tích 1' WHERE course_code = 'MA001IU';
UPDATE course SET name_vn = 'Giải tích 2' WHERE course_code = 'MA003IU';
UPDATE course SET name_vn = 'Giải tích 3' WHERE course_code = 'MA023IU';
UPDATE course SET name_vn = 'Phương trình vi phân' WHERE course_code = 'MA024IU';
UPDATE course SET name_vn = 'Xác suất, Thống kê và Quá trình ngẫu nhiên' WHERE course_code = 'MA026IU';
UPDATE course SET name_vn = 'Tư duy phản biện' WHERE course_code = 'PE008IU';
UPDATE course SET name_vn = 'Khoa học môi trường' WHERE course_code = 'PE014IU';
UPDATE course SET name_vn = 'Triết học Mác - Lênin' WHERE course_code = 'PE015IU';
UPDATE course SET name_vn = 'Kinh tế chính trị Mác - Lênin' WHERE course_code = 'PE016IU';
UPDATE course SET name_vn = 'Chủ nghĩa xã hội khoa học' WHERE course_code = 'PE017IU';
UPDATE course SET name_vn = 'Lịch sử Đảng Cộng sản Việt Nam' WHERE course_code = 'PE018IU';
UPDATE course SET name_vn = 'Đạo đức kỹ thuật và Kỹ năng nghề nghiệp' WHERE course_code = 'PE020IU';
UPDATE course SET name_vn = 'Vật lý 4' WHERE course_code = 'PH012IU';
UPDATE course SET name_vn = 'Vật lý 1 (Cơ học tổng quát)' WHERE course_code = 'PH013IU';
UPDATE course SET name_vn = 'Vật lý 2 (Cơ lưu chất và Nhiệt học)' WHERE course_code = 'PH014IU';
UPDATE course SET name_vn = 'Vật lý 3 (Điện và Từ)' WHERE course_code = 'PH015IU';
UPDATE course SET name_vn = 'Thực hành Vật lý 3' WHERE course_code = 'PH016IU';
UPDATE course SET name_vn = 'Giáo dục thể chất 1' WHERE course_code = 'PT001IU';
UPDATE course SET name_vn = 'Giáo dục thể chất 2' WHERE course_code = 'PT002IU';

COMMIT;
